#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc
# Add .NET Core SDK tools
export PATH="$PATH:/home/luuk/.dotnet/tools"

# do not edit this file. put files in the dir below.
#source ~/.bashrc
for FN in $HOME/Library/profile.d/*.sh ; do
    source "$FN"
done
