#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

command_exists () {
    type "$1" &> /dev/null ;
}

# do not edit this file. put files in the dir below.
for FN in $HOME/.bashrc.d/*.sh ; do
    source "$FN"
done
